# Generated by Django 5.2.7 on 2026-01-08 12:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_afiliacion', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Afiliación/Cédula')),
                ('saldo_horas_comp', models.DurationField(default=datetime.timedelta(0), verbose_name='Saldo Horas Compensatorias')),
                ('nivel', models.IntegerField(choices=[(1, 'Empleado (Solo registro propio)'), (2, 'Supervisor de Turno'), (3, 'Jefe de Departamento'), (4, 'Administrador RH'), (5, 'Superadmin')], default=1, verbose_name='Nivel de Acceso')),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Empleado',
                'verbose_name_plural': 'Perfiles Empleados',
            },
        ),
        migrations.CreateModel(
            name='RegistroJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('salida', models.TimeField(blank=True, null=True)),
                ('horas_netas', models.DurationField(blank=True, null=True)),
                ('horas_extras', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('salida_forzada', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('empleado', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_libre', models.DateField()),
                ('horas_solicitadas', models.DurationField(default=datetime.timedelta(seconds=28800))),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Día Libre',
                'verbose_name_plural': 'Solicitudes de Días Libres',
                'unique_together': {('empleado', 'fecha_libre')},
            },
        ),
    ]
