# Generated by Django 5.2.7 on 2026-01-09 19:37

import clientes.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('ruc', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReporteAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reporte', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('fecha_asistencia', models.DateField(verbose_name='Fecha de asistencia')),
                ('maquina', models.CharField(max_length=200)),
                ('persona_solicita', models.CharField(max_length=200)),
                ('problema', models.TextField()),
                ('problema_encontrado', models.TextField()),
                ('solucion', models.TextField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='clientes.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Asistencia',
                'verbose_name_plural': 'Reportes de Asistencia',
                'ordering': ['-fecha_asistencia'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=clientes.models.reporte_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('tipo', models.CharField(blank=True, choices=[('foto', 'Fotografía'), ('pdf', 'Documento PDF')], max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='clientes.reporteasistencia')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
