# Generated by Django 5.2.7 on 2025-12-10 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('CodigoProducto', models.CharField(db_column='CodigoProducto', max_length=50, primary_key=True, serialize=False, verbose_name='SKU')),
                ('Producto', models.CharField(db_column='Producto', max_length=255, verbose_name='Nombre del Producto')),
                ('Marca', models.CharField(blank=True, db_column='Marca', max_length=100, null=True, verbose_name='Marca')),
                ('Modelo', models.CharField(blank=True, db_column='Modelo', max_length=100, null=True, verbose_name='Modelo/Especificación')),
                ('Descripcion', models.TextField(blank=True, db_column='Descripcion', null=True, verbose_name='Descripción Detallada')),
                ('Cantidad', models.FloatField(db_column='Cantidad', default=0.0, verbose_name='Stock Actual')),
                ('Ubicacion', models.CharField(blank=True, db_column='Ubicacion', max_length=100, null=True, verbose_name='Ubicación')),
                ('MinimoAdmisible', models.FloatField(db_column='MinimoAdmisible', default=0.0, verbose_name='Stock Mínimo')),
                ('MaximoAdmisible', models.FloatField(db_column='MaximoAdmisible', default=0.0, verbose_name='Stock Máximo')),
                ('PrecioGS', models.FloatField(db_column='PrecioGS', default=0.0, verbose_name='Precio Unitario (G$)')),
                ('PrecioUSD', models.FloatField(db_column='PrecioUSD', default=0.0, verbose_name='Precio Unitario (USD)')),
                ('PrecioTotalGS', models.FloatField(db_column='PrecioTotalGS', default=0.0, verbose_name='Valor Total de Stock (G$)')),
                ('FechaUltimoMovimiento', models.DateTimeField(db_column='FechaUltimoMovimiento', default=django.utils.timezone.now, verbose_name='Último Movimiento')),
            ],
            options={
                'verbose_name': 'Producto de Inventario',
                'verbose_name_plural': 'Productos de Inventario',
                'db_table': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Recepción)'), ('SALIDA', 'Salida (Venta/Uso)'), ('AJUSTE', 'Ajuste de Inventario')], default='AJUSTE', max_length=10, verbose_name='Tipo de Movimiento')),
                ('cantidad_movida', models.FloatField(verbose_name='Cantidad')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo/Referencia')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Unitario Registrado')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo Total del Movimiento (GS)')),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tasa de Cambio (GS/USD)')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia/Factura')),
                ('producto', models.ForeignKey(db_column='CodigoProducto', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='compras.inventario')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'StockMovement',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
