# Generated by Django 5.2.7 on 2025-12-16 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('proveedor', models.CharField(max_length=255, verbose_name='Nombre del Proveedor')),
                ('ruc_proveedor', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC del Proveedor')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total')),
                ('pdf_original', models.FileField(upload_to='facturas/originales/', verbose_name='PDF Original Cargado')),
                ('pdf_registro', models.FileField(blank=True, null=True, upload_to='facturas/registros/', verbose_name='PDF de Registro Generado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Procesamiento'), ('procesada', 'Procesada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Cargó')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad Recibida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Subtotal')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='compras.factura', verbose_name='Factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_recibidas', to='compras.inventario', verbose_name='Producto del Inventario')),
            ],
            options={
                'verbose_name': 'Producto en Factura',
                'verbose_name_plural': 'Productos en Factura',
                'db_table': 'FacturaProducto',
                'indexes': [models.Index(fields=['factura'], name='FacturaProd_factura_af518a_idx'), models.Index(fields=['producto'], name='FacturaProd_product_b14620_idx')],
            },
        ),
    ]
