# Generated by Django 5.2.7 on 2025-12-17 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='compras.proveedor', verbose_name='Proveedor'),
        ),
    ]
