# Generated by Django 5.2.7 on 2026-01-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_factura_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='pdf_registro',
            field=models.FileField(blank=True, null=True, upload_to='facturas/registros/%Y/%m/', verbose_name='Archivo PDF'),
        ),
    ]
